openapi: 3.0.0
info:
  title: safe-courier
  description: Safe Courier is a courier service that helps users deliver parcels to different destinations.
  contact:
    name: Atuhaire Collins
    email: collinsbenda360@gmail.com
  version: '1.0'
servers:
  - url: http://localhost:5000/api/v1
    variables: {}
paths:
  /auth/signup:
    post:
      tags:
        - auth
      summary: signup
      operationId: signup
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signuprequest'
            example:
              name: atuhaire3
              email: collinsbenda3300@gmail.com
              password: password
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/signin:
    post:
      tags:
        - auth
      summary: signin
      operationId: signin
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signinrequest'
            example:
              email: collinsbenda3300@gmail.com
              password: password
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /users:
    get:
      tags:
        - Users
      summary: get all users
      operationId: getallusers
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /users/619df35dfbfdf1e5a6ebabd8:
    get:
      tags:
        - Users
      summary: get  user by id
      operationId: getuserbyid
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /users/61a090c272e27fdff8bf75a5:
    put:
      tags:
        - Users
      summary: update user by id
      operationId: updateuserbyid
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateuserbyidrequest'
            example:
              email: collinsbenda36000@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    delete:
      tags:
        - Users
      summary: delete user parcels
      operationId: deleteuserparcels
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /parcels:
    get:
      tags:
        - Parcels
      summary: get all parcels
      operationId: getallparcels
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    post:
      tags:
        - Parcels
      summary: create parcel
      operationId: createparcel
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createparcelrequest'
            example:
              receiver:
                name: collins
                email: collins2@gmail.com
                phoneNumber: 0770567432
                address: kampala
              _id: 61a09d1832f0da1db182254f
              parcelType: safeCaurier
              description: delivery app
              weight: 10
              weightUnit: kgs
              sender: 61a0a791c32916c03bdb0d95
              pickupLocation: usa
              destination: kampala
              presentLocation: kampala
              status: processing
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /parcels/61a0bb50acbdb2f715f18845:
    get:
      tags:
        - Parcels
      summary: get specific parcel
      operationId: getspecificparcel
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    delete:
      tags:
        - Parcels
      summary: cancel parcel
      operationId: cancelparcel
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /parcels/61a0bb50acbdb2f715f18845/presentlocation:
    put:
      tags:
        - Parcels
      summary: get  parcel  present location
      operationId: getparcelpresentlocation
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getparcelpresentlocationrequest'
            example:
              presentLocation: lira
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /parcels/61a0bb50acbdb2f715f18845/destination:
    put:
      tags:
        - Parcels
      summary: get  parcel  destination
      operationId: getparceldestination
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getparceldestinationrequest'
            example:
              destination: arua
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
components:
  schemas:
    signuprequest:
      title: signuprequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: atuhaire3
        email: collinsbenda3300@gmail.com
        password: password
    signinrequest:
      title: signinrequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: collinsbenda3300@gmail.com
        password: password
    updateuserbyidrequest:
      title: updateuserbyidrequest
      required:
        - email
      type: object
      properties:
        email:
          type: string
      example:
        email: collinsbenda36000@gmail.com
    deleteuserparcelsrequest:
      title: deleteuserparcelsrequest
      required:
        - email
      type: object
      properties:
        email:
          type: string
      example:
        email: collinsbenda36000@gmail.com
    deleteuserbyidrequest:
      title: deleteuserbyidrequest
      required:
        - email
      type: object
      properties:
        email:
          type: string
      example:
        email: collinsbenda36000@gmail.com
    getparcelpresentlocationrequest:
      title: getparcelpresentlocationrequest
      required:
        - presentLocation
      type: object
      properties:
        presentLocation:
          type: string
      example:
        presentLocation: lira
    getparceldestinationrequest:
      title: getparceldestinationrequest
      required:
        - destination
      type: object
      properties:
        destination:
          type: string
      example:
        destination: arua
    cancelparcelrequest:
      title: cancelparcelrequest
      required:
        - destination
      type: object
      properties:
        destination:
          type: string
      example:
        destination: arua
    createparcelrequest:
      title: createparcelrequest
      required:
        - receiver
        - _id
        - parcelType
        - description
        - weight
        - weightUnit
        - sender
        - pickupLocation
        - destination
        - presentLocation
        - status
      type: object
      properties:
        receiver:
          $ref: '#/components/schemas/Receiver'
        _id:
          type: string
        parcelType:
          type: string
        description:
          type: string
        weight:
          type: integer
          format: int32
        weightUnit:
          type: string
        sender:
          type: string
        pickupLocation:
          type: string
        destination:
          type: string
        presentLocation:
          type: string
        status:
          type: string
      example:
        receiver:
          name: collins
          email: collins2@gmail.com
          phoneNumber: 0770567432
          address: kampala
        _id: 61a09d1832f0da1db182254f
        parcelType: safeCaurier
        description: delivery app
        weight: 10
        weightUnit: kgs
        sender: 61a0a791c32916c03bdb0d95
        pickupLocation: usa
        destination: kampala
        presentLocation: kampala
        status: processing
    Receiver:
      title: Receiver
      required:
        - name
        - email
        - phoneNumber
        - address
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        address:
          type: string
      example:
        name: collins
        email: collins2@gmail.com
        phoneNumber: 0770567432
        address: kampala
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: auth
  - name: Users
  - name: Parcels
